### ISSUE TITLE
Observation - EffectiveDateTime

### ISSUE THREAD

**Issue by quastkj** [medizininformatik-initiative/Projectathon7-VHF-DataExtraction#8]
Hallo,
nach Rücksprache und Sichtung der Resultate dieser Skripte mit unserem DSB ist aufgefallen, dass in
"resourceType": "Observation"
die Eintragungen
"effectiveDateTime": 
nicht vergröbert sind, also ein Identifizierungs-Risiko vorliegt. 
Eine Vergröberung ähnlich wie für Encounter wäre aus Sicht unseres DSB ausreichend.
Wäre eine Vergröberung seitens der Analysten tolerierbar?

**Comment by juliangruendner** [comment]
@astruebi  - is this possible from a analysis perspective?

**Comment by juliangruendner** [comment]
@quastkj  - the data extraction can be configured to apply this type of obfuscation, by adding the following to the 
psd_config.json as part of the entry with the name : "psd_name": "obs"
```
"apply_function": [
      {
        "function_to_apply": "obfuscate_date_to_day",
        "path_to_field": "effectiveDateTime"
      }
    ]
```

**Comment by quastkj** [comment]
Thank you, we have proceeded as suggested.
Perhaps you could update psd_config.json.default to obfuscate any potentially identifying entries. As far as the analysts agree, this would be helpful for upcoming sites.

**Comment by astruebi** [comment]
Changing the correct time of the observation should not be a problem, if you **make sure that the Encounter start date is always day-exact**. Otherwise problems may occur.

Observations are assigned to encounters in 2 ways:
1.) The observation references the Encounter directly -> the time of the observation is irrelevant.
2) If the optional reference from 1.) is not available, then the observation is assigned to the Encounter whose start date is the shortest before the date of the Encounter. I.e. by truncating the time, which corresponds to a reset to 0:00, the observation can slip before the start of the Encounter, if the Encounter start date contains a time.

There are DIC where only some or no observations have the reference to the Encounter.
